export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST"
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";
export const TOGGLE_ISFAVORITE = "TOGGLE_ISFAVORITE";
export const FETCH_BY_AUTHORS = "FETCH_BY_AUTHORS";
export const FETCH_BY_CATEGORIES = "FETCH_BY_CATEGORIES";
export const PAGINATION = "PAGINATION";
